version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: deploy/before_install.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: deploy/restart_server.sh
      timeout: 300
      runas: ubuntu
